### ISSUE TITLE
Confusion regarding to how classification accuracy is evaluated

### ISSUE THREAD

**Issue by linzhiqiu** [allenai/gpv2#1]
From the description of GPV-2, it seems for classification task, the model output is simply the decoder output which could be arbitrary text. Then how is the classification performance evaluated? For example, "bee" and "bees" seem equally correct as an image label. Or perhaps I misunderstood the paper?

**Comment by chrisc36** [comment]
Good question, for classification we have the model compute the log-probability of each output class and then select the highest-scoring class. That way the model will always pick a valid output class.
