### ISSUE TITLE
Issue regarding downloading the pre-trained models from AWS

### ISSUE THREAD

**Issue by NavidRajabi** [allenai/gpv2#2]
When I run the following command:
`aws s3 cp --recursive s3://ai2-prior-gpv/public/gpv2-models/gpv2 models/gpv2`

I face the following error:
`fatal error: Unable to locate credentials`

So, I was wondering if someone could help me out on that.

**Comment by chrisc36** [comment]
Try the --no-sign-request flag.

aws s3 cp --no-sign-request --recursive s3://ai2-prior-gpv/public/gpv2-models/gpv2 models/gpv2
