### ISSUE TITLE
Can I train gpv2 on Visual Grounding via loc?

### ISSUE THREAD

**Issue by h-ccc** [allenai/gpv2#3]
Great work here! 
I find that gpv2 can be well transferred to Visual Grounding as is shown in Supplementary Material and [UnifiedIO](https://unified-io.allenai.org). However, I encountered some performance related problems, when I use `Localization` to train gpv2 on RefCOCO. Specifically, I use the checkpoint trained with web data to init the model and use the default hyper parameters.
Could you please tell me how to train gpv2 on Visual Grounding? 
Thanks in advance!

**Comment by chrisc36** [comment]
In essence, I think the way to do that would be to treat refexp as a  localization query but with a more complex input query and with only a single bounding box returned as output. Basically each refexp example could become a `LocalizationExample with a single output box and with the referring expression as the category.
